ContactBundle\Entity\Contact:
    properties:
        firstname:
            - NotBlank: ~
            - NotNull: ~
        lastname:
            - NotBlank: ~
            - NotNull: ~
        email1:
            - NotBlank: ~
            - NotNull: ~