ContactBundle\Entity\Contact:
    properties:
        firstname:
            - NotBlank: ~
        lastname:
            - NotBlank: ~
        email1:
            - NotBlank: ~
            - Email: 
                message: The email is not a valid email.
                checkMX: true 
